[package]
name = "modbus_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
serial = "0.4.0"
serialport = "4.3.0"

